apiVersion: v1
kind: Secret
metadata:
  name: pulse-secrets
  namespace: pulse
type: Opaque
data:
  # JWT Secret (shared across all services)
  jwt-secret: NWI0MWQ2YTBjMWFkZmQyODA0ZDczMGQyNmY3YTRmZDE=
  
  # PostgreSQL credentials
  postgres-auth-password: cHVsc2VfYXV0aA==
  postgres-user-password: cHVsc2VfdXNlcg==
  postgres-root-password: cHVsc2VfdXNlcg==
  
  # MongoDB credentials
  mongodb-username: cHVsc2VfdXNlcg==
  mongodb-password: cHVsc2VfdXNlcg==
  
  # RabbitMQ credentials
  rabbitmq-username: Z3Vlc3Q=
  rabbitmq-password: Z3Vlc3Q=
  
  # Admin credentials
  admin-email: YWRtaW5AcHVsc2UuY29t
  admin-password: YWRtaW4xMjM=
  
  # Session secret
  session-secret: ZGV2LXNlc3Npb24tc2VjcmV0LWNoYW5nZS1pbi1wcm9kdWN0aW9u




