apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: pulse
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_PUBLIC_API_URL: "http://localhost:8000"
  NEXT_PUBLIC_WS_URL: "ws://localhost:8084"




