apiVersion: v1
kind: ConfigMap
metadata:
  name: post-service-config
  namespace: pulse
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "pulse_user"
  DB_NAME: "pulse_posts"
  DB_SSLMODE: "disable"
  PORT: "8082"
  LOG_LEVEL: "info"




